### ISSUE TITLE
Blood Shard Hand Ins, Mangletooth

### ISSUE THREAD

**Issue by Jimmeh93** [NexusWoW/Nexus-WoW#20]
The Quests in the Barrens, Camp Taurajo from Mangletooth
Feed him shards to receive a selected buff, but do not receive the buffs

![wowscrnshot_012917_144505](https://cloud.githubusercontent.com/assets/25411653/22401938/69be3d8a-e632-11e6-9aaf-dedcd516f4e4.jpg)

**Comment by h0rs** [comment]
Hey @Jimmeh93,

This is certainly a funny one :) If you open the cage before you hit complete the spell should go off :)

The reason they are not working is because Mangletooth cannot cast the spell on you, due to the cage being a line of sight object.

I'll fix these spells to ignore LoS.

Thanks for your report mate.
